<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsAspireHost>true</IsAspireHost>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\ApiGateway\MultiShop.OcelotGateway\MultiShop.OcelotGateway.csproj" />
        <ProjectReference Include="..\Frontends\MultiShop.WebUI\MultiShop.WebUI.csproj" />
        <ProjectReference Include="..\IdentityServer\MultiShop.IdentityServer\MultiShop.IdentityServer.csproj" />
        <ProjectReference Include="..\Services\Basket\MultiShop.Basket\MultiShop.Basket.csproj" />
        <ProjectReference Include="..\Services\Cargo\MultiShop.Cargo.WebApi\MultiShop.Cargo.WebApi.csproj" />
        <ProjectReference Include="..\Services\Catalog\MultiShop.Catalog\MultiShop.Catalog.csproj" />
        <ProjectReference Include="..\Services\Comment\MultiShop.Comment\MultiShop.Comment.csproj" />
        <ProjectReference Include="..\Services\Discount\MultiShop.Discount\MultiShop.Discount.csproj" />
        <ProjectReference Include="..\Services\Order\Presentation\MultiShop.Order.API\MultiShop.Order.API.csproj" />
        <ProjectReference Include="..\Services\Payment\MultiShop.Payment\MultiShop.Payment.csproj" />
    </ItemGroup>

</Project>
